name: 'functions-tests'
on:
  pull_request:

defaults:
  run:
    working-directory: ./supabase/tests/functions

env:
  SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN: ${{ secrets.SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.77.9
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.36.4
      - run: supabase start
      - run: supabase functions serve &
      - run: deno test --allow-all hello-world-test.ts
