name: 'functions-tests'
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.77.9
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.36.4
      - run: supabase start
      - run: |
          echo -e "ONESIGNAL_APP_ID=${{ secrets.ONESIGNAL_APP_ID }}\nONESIGNAL_REST_API_KEY=${{ secrets.ONESIGNAL_REST_API_KEY }}\nONESIGNAL_USER_AUTH_KEY=${{ secrets.ONESIGNAL_USER_AUTH_KEY }}" > .env
          echo -e "STRIPE_API_KEY=${{ secrets.STRIPE_API_KEY }}\nSTRIPE_CREDIT_PRICE_ID=${{ secrets.STRIPE_CREDIT_PRICE_ID }}\nSTRIPE_WEBHOOK_SIGNING_SECRET=${{ secrets.STRIPE_WEBHOOK_SIGNING_SECRET }}" >> .env
          supabase functions serve --no-verify-jwt --env-file $PWD/.env &
        working-directory: ./supabase
      - run: |
          supabase status -o env | sed  's/^/SUPABASE_/' > .env
          echo -e "STRIPE_WEBHOOK_SIGNING_SECRET=${{ secrets.STRIPE_WEBHOOK_SIGNING_SECRET }}" >> .env
          deno test --allow-all
        working-directory: ./supabase/tests/functions
